Linkage of collection camps to a particular user in their profile
ColoredCow/goonj pull request #193
Opened 2024-09-10 07:43 UTC by tarunnjoshi

Linkage of collection camps to a particular user in their profile

2024-09-10 14:06 UTC, pokhiii requested changes

2024-09-11 04:21 UTC, tarunnjoshi commented on wp-content/civi-extensions/goonjcustom/Civi/CollectionCampService.php
> +          ->addValue('activity_date_time', date('YmdHis'))
Yes it's correct

2024-09-11 04:46 UTC, tarunnjoshi commented on wp-content/civi-extensions/goonjcustom/Civi/CollectionCampService.php
> +          ->addValue('subject', $collectionCampTitle)
For this i have followed the below steps:
1. Create a Custom Field Group for Activities (Collection Camp Data)
2. Add a Custom Field for Collection Camp Data
3. Custom field with a name like "Collection Camp ID" and set its data type to "Integer"
4. Save the id through API `->addValue('Collection_Camp_Data.Collection_Camp_ID', $collectionCampId)`

2024-09-12 11:46 UTC, pokhiii approved these changes

2024-09-12 11:46 UTC, pokhiii commented on wp-content/civi-extensions/goonjcustom/Civi/CollectionCampService.php
> +        ->addValue('activity_type_id', $collectionCampActivityId)
```suggestion
        ->addValue('activity_type_id:name', 'Organize Collection Camp')
```

2024-09-12 11:46 UTC, pokhiii commented on wp-content/civi-extensions/goonjcustom/Civi/CollectionCampService.php
> +    $collectionCampActivityId = $optionValues->first()['value'];
Let's remove this and directly use the label 'Organize Collection Camp' in the query

2024-09-12 11:46 UTC, pokhiii commented on wp-content/civi-extensions/goonjcustom/Civi/CollectionCampService.php
> +        ->addValue('status_id', 2)
```suggestion
        ->addValue('status_id:name', 'complete') // whatever is the name of the status you want to use
```

2024-09-12 11:46 UTC, pokhiii commented on wp-content/civi-extensions/goonjcustom/Civi/CollectionCampService.php
> +        ->addValue('activity_date_time', date('YmdHis'))
is this storing the time correctly? shouldn't we use more standard format
```suggestion
        ->addValue('activity_date_time', date('Y-m-d H:i:s'))
```

2024-09-12 11:55 UTC, merged